[theme]
base = "dark"
primaryColor = "#00AAFF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
[client]
showSidebarNavigation = false
toolbarMode = "minimal"
[server]
headless = false
[browser]
gatherUsageStats = false